### ISSUE TITLE
systemctl: not found

### ISSUE THREAD

**Issue by vialcollet** [nsg/ansible-graphite#14]
I am trying to install graphite using your role on Debian Jessie.
I am using defaults for most options except user and passwords.
Here is the error I get from the Relaod systemd if unit file has changed:

```
TASK [nsg.graphite : Reload systemd if unit file has changed] ******************
fatal: [monitoring.curuba.fr]: FAILED!
```

``` JSON
{"changed": true, "cmd": "systemctl daemon-reload", 
"delta": "0:00:00.001284", 
"end": "2016-04-04 09:34:38.225001",
"failed": true, 
"rc": 127, 
"start": "2016-04-04 09:34:38.223717", 
"stderr": "/bin/sh: 1: systemctl: not found", 
"stdout": "", 
"stdout_lines": [], 
"warnings": []
```

Any idea?

Thanks in advance

**Comment by nsg** [comment]
Thank you for the report, I will test it on Jessie later today.

**Comment by vialcollet** [comment]
Thanks!
Also after re-running the playbook, I get this error on the restart carbon-cache:

```
no service or tool found for: carbon-cache
```

**Comment by nsg** [comment]
I tried with two new fresh Debian Jessie installs (8.3), with a fresh checkout of master, and this play:

```
---

- hosts: all
  roles:
    - role: ansible-graphite
      graphite_secret_key: 'dgdgdfgasg'
      uwsgi_graphite_extraopts:
        - option: http
          value: "{{ ansible_default_ipv4.address }}:8080"
```

Ansible 1.9.0.1 installed cleanly without any problem, but with 2.0.1.0 I get a internal server error in the browser after a successful install, it's probably some change in the templating engine in 2.x I guess. I will investigate that. https://github.com/nsg/ansible-graphite/issues/15

Your problem sounds like something completely different, sounds like Ansible is unable to find the startup scripts or systemd, Debian 8+ is supposed to use systemd (systemctl) so it's a little confusing.

Maybe you have upgraded your install from Debian 7 or any older pre-systemd version?
