### ISSUE TITLE
Problem with ansible 2 and uwsgi

### ISSUE THREAD

**Issue by nsg** [nsg/ansible-graphite#15]
Did a fresh install on Debian 8.3 on DO with latest Ansible and got a internal server error in the browser. If I do a identical install but use the good old version 1.9 everything works. Investigate.

```

---

- hosts: all
  roles:
    - role: ansible-graphite
      graphite_secret_key: 'dgdgdfgasg'
      uwsgi_graphite_extraopts:
        - option: http
          value: "{{ ansible_default_ipv4.address }}:8080"
```
