### ISSUE TITLE
sudo: a password is required - django-admin.py inspectdb

### ISSUE THREAD

**Issue by TinajaLabs** [nsg/ansible-graphite#36]
Running on Centos 7

```
$  ansible --version
ansible 2.7.1
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

```
fatal:
  [charts]:
    FAILED! => {
      "changed": false,
      ` "module_stderr": "Shared connection to <ipaddress> closed.\r\n",
      "module_stdout": "\u001b]0;c7h-template.cbase.ecm\u0007sudo: a password is required\r\n",
      "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
      "rc": 1
    }
```

When running this part of django-admin.yml
```
- name: django-admin.py - Inspect graphite db
  command: django-admin.py inspectdb
  environment:
    DJANGO_SETTINGS_MODULE: graphite.settings
    PYTHONPATH: "{{ graphite_install_path}}/webapp/"
  become: true
  become_user: "{{ graphite_user }}"
  register: result
  changed_when: false
```

Any tips appreciated,
Chris.
